import { Command } from 'commander';
import * as readline from 'node:readline';
import { existsSync, mkdirSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

interface InitOptions {
  providers: {
    ollama: boolean;
    anthropic: { enabled: boolean; apiKey?: string };
    openai: { enabled: boolean; apiKey?: string };
    google: { enabled: boolean; apiKey?: string };
  };
  budget: string;
  preferLocal: boolean;
  serverPort: number;
}

function ask(rl: readline.Interface, question: string, fallback?: string): Promise<string> {
  const hint = fallback ? ` [${fallback}]` : '';
  return new Promise((res) => {
    rl.question(`${question}${hint}: `, (answer) => {
      res(answer.trim() || fallback || '');
    });
  });
}

function buildProviderPriority(opts: InitOptions): { slm: string[]; llm: string[] } {
  const isOn = (name: string): boolean => {
    if (name === 'ollama') return opts.providers.ollama;
    return (opts.providers[name as 'anthropic' | 'openai' | 'google'] as { enabled: boolean }).enabled;
  };
  return {
    slm: ['ollama', 'google', 'openai', 'anthropic'].filter(isOn),
    llm: ['anthropic', 'openai', 'google'].filter(isOn),
  };
}

function generateConfigYaml(opts: InitOptions): string {
  const lines: string[] = [];

  lines.push('# Joule Configuration');
  lines.push('# Generated by `joule init` — edit freely');
  lines.push('# Docs: https://github.com/Aagam-Bothara/Joule');
  lines.push('');

  // ── Providers ──────────────────────────────────────────
  lines.push('# ── Providers ────────────────────────────────────────────');
  lines.push('providers:');

  if (opts.providers.ollama) {
    lines.push('  ollama:');
    lines.push('    enabled: true');
    lines.push('    baseUrl: "http://localhost:11434"');
    lines.push('    models:');
    lines.push('      slm: "llama3.2:3b"');
  }

  if (opts.providers.anthropic.enabled) {
    lines.push('');
    lines.push('  anthropic:');
    lines.push('    enabled: true');
    if (opts.providers.anthropic.apiKey) {
      lines.push(`    apiKey: "${opts.providers.anthropic.apiKey}"`);
    } else {
      lines.push('    # apiKey: set via JOULE_ANTHROPIC_API_KEY env var');
    }
    lines.push('    models:');
    lines.push('      slm: "claude-haiku-4-5-20251001"');
    lines.push('      llm: "claude-sonnet-4-20250514"');
  }

  if (opts.providers.openai.enabled) {
    lines.push('');
    lines.push('  openai:');
    lines.push('    enabled: true');
    if (opts.providers.openai.apiKey) {
      lines.push(`    apiKey: "${opts.providers.openai.apiKey}"`);
    } else {
      lines.push('    # apiKey: set via JOULE_OPENAI_API_KEY env var');
    }
    lines.push('    models:');
    lines.push('      slm: "gpt-4o-mini"');
    lines.push('      llm: "gpt-4o"');
  }

  if (opts.providers.google.enabled) {
    lines.push('');
    lines.push('  google:');
    lines.push('    enabled: true');
    if (opts.providers.google.apiKey) {
      lines.push(`    apiKey: "${opts.providers.google.apiKey}"`);
    } else {
      lines.push('    # apiKey: set via JOULE_GOOGLE_API_KEY env var');
    }
    lines.push('    models:');
    lines.push('      slm: "gemini-2.0-flash"');
    lines.push('      llm: "gemini-2.5-pro"');
  }

  lines.push('');

  // ── Budget ─────────────────────────────────────────────
  lines.push('# ── Budget ───────────────────────────────────────────────');
  lines.push('# Presets: low ($0.01), medium ($0.10), high ($1.00), unlimited ($10)');
  lines.push(`budgets:`);
  lines.push(`  default: "${opts.budget}"`);
  lines.push('');

  // ── Routing ────────────────────────────────────────────
  const prio = buildProviderPriority(opts);
  const slmList = prio.slm.map(s => `"${s}"`).join(', ');
  const llmList = prio.llm.map(s => `"${s}"`).join(', ');

  lines.push('# ── Routing ──────────────────────────────────────────────');
  lines.push('routing:');
  lines.push(`  preferLocal: ${opts.preferLocal}`);
  lines.push('  slmConfidenceThreshold: 0.6    # 0-1, when to use small vs large model');
  lines.push('  complexityThreshold: 0.7        # 0-1, task complexity threshold');
  lines.push('  providerPriority:');
  lines.push(`    slm: [${slmList}]`);
  lines.push(`    llm: [${llmList}]`);
  lines.push('');

  // ── Energy ─────────────────────────────────────────────
  lines.push('# ── Energy tracking ──────────────────────────────────────');
  lines.push('energy:');
  lines.push('  enabled: true');
  lines.push('  gridCarbonIntensity: 400         # gCO2/kWh — adjust for your region');
  lines.push('  localModelCarbonIntensity: 0     # local models use your own power');
  lines.push('  includeInRouting: false');
  lines.push('  energyWeight: 0.3');
  lines.push('');

  // ── Tools ──────────────────────────────────────────────
  lines.push('# ── Tools ────────────────────────────────────────────────');
  lines.push('tools:');
  lines.push('  builtinEnabled: true');
  lines.push('  pluginDirs: []');
  lines.push('  disabledTools: []');
  lines.push('');

  // ── Logging ────────────────────────────────────────────
  lines.push('# ── Logging ──────────────────────────────────────────────');
  lines.push('logging:');
  lines.push('  level: "info"                    # debug | info | warn | error');
  lines.push('  traceOutput: "memory"            # memory | file | both');
  lines.push('');

  // ── Server ─────────────────────────────────────────────
  lines.push('# ── Server ───────────────────────────────────────────────');
  lines.push('server:');
  lines.push(`  port: ${opts.serverPort}`);
  lines.push('  host: "127.0.0.1"');
  lines.push('');

  return lines.join('\n');
}

export const initCommand = new Command('init')
  .description('Set up a new Joule project — generates joule.config.yaml')
  .option('-y, --yes', 'Accept all defaults without prompting')
  .option('--force', 'Overwrite existing config file')
  .action(async (cmdOpts) => {
    const configPath = resolve('joule.config.yaml');
    const jouleDir = resolve('.joule');

    // Guard against overwriting existing config
    if (existsSync(configPath) && !cmdOpts.force) {
      const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
      const answer = await ask(rl, 'joule.config.yaml already exists. Overwrite? (y/N)', 'N');
      rl.close();
      if (answer.toLowerCase() !== 'y') {
        console.log('Aborted. Use --force to overwrite.');
        return;
      }
    }

    let options: InitOptions;

    if (cmdOpts.yes) {
      // Non-interactive — all defaults
      options = {
        providers: {
          ollama: true,
          anthropic: { enabled: false },
          openai: { enabled: false },
          google: { enabled: false },
        },
        budget: 'medium',
        preferLocal: true,
        serverPort: 3927,
      };
    } else {
      const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

      console.log('');
      console.log('  Joule Project Setup');
      console.log('  ===================');
      console.log('');

      // Q1: Providers
      console.log('  Which providers do you want to use?');
      console.log('    1. ollama     — local, free (needs Ollama running)');
      console.log('    2. anthropic  — Claude (needs API key)');
      console.log('    3. openai     — GPT (needs API key)');
      console.log('    4. google     — Gemini (needs API key)');
      console.log('');
      const providerInput = await ask(rl, '  Enter numbers, comma-separated', '1');
      const picks = providerInput.split(',').map(s => s.trim());

      let useOllama = picks.includes('1');
      const useAnthropic = picks.includes('2');
      const useOpenai = picks.includes('3');
      const useGoogle = picks.includes('4');

      // If nothing valid was selected, fall back to ollama
      if (!useOllama && !useAnthropic && !useOpenai && !useGoogle) {
        console.log('  No valid selection — defaulting to ollama.');
        useOllama = true;
      }

      console.log('');

      // Q2: API keys (conditional)
      let anthropicKey: string | undefined;
      let openaiKey: string | undefined;
      let googleKey: string | undefined;

      if (useAnthropic) {
        anthropicKey = (await ask(rl, '  Anthropic API key (Enter to skip — set env var later)')) || undefined;
      }
      if (useOpenai) {
        openaiKey = (await ask(rl, '  OpenAI API key (Enter to skip — set env var later)')) || undefined;
      }
      if (useGoogle) {
        googleKey = (await ask(rl, '  Google API key (Enter to skip — set env var later)')) || undefined;
      }

      if (useAnthropic || useOpenai || useGoogle) console.log('');

      // Q3: Budget
      const budget = await ask(rl, '  Default budget (low / medium / high / unlimited)', 'medium');
      const validBudgets = ['low', 'medium', 'high', 'unlimited'];
      const finalBudget = validBudgets.includes(budget) ? budget : 'medium';

      // Q4: Prefer local
      const localPref = await ask(rl, '  Prefer local models over cloud? (Y/n)', 'Y');
      const preferLocal = localPref.toLowerCase() !== 'n';

      // Q5: Server port
      const portInput = await ask(rl, '  Server port', '3927');
      const serverPort = parseInt(portInput, 10) || 3927;

      rl.close();

      options = {
        providers: {
          ollama: useOllama,
          anthropic: { enabled: useAnthropic, apiKey: anthropicKey },
          openai: { enabled: useOpenai, apiKey: openaiKey },
          google: { enabled: useGoogle, apiKey: googleKey },
        },
        budget: finalBudget,
        preferLocal,
        serverPort,
      };
    }

    // Generate and write config
    const yaml = generateConfigYaml(options);
    await writeFile(configPath, yaml, 'utf-8');
    console.log('');
    console.log(`  Created ${configPath}`);

    // Create .joule/ directory
    if (!existsSync(jouleDir)) {
      mkdirSync(jouleDir, { recursive: true });
      console.log(`  Created ${jouleDir}/`);
    }

    // Next steps
    console.log('');
    console.log('  Next steps:');

    let step = 1;
    console.log(`    ${step++}. Review joule.config.yaml and tweak if needed`);

    if (options.providers.ollama) {
      console.log(`    ${step++}. Make sure Ollama is running: ollama serve`);
    }
    if (options.providers.anthropic.enabled && !options.providers.anthropic.apiKey) {
      console.log(`    ${step++}. Set your Anthropic key: export JOULE_ANTHROPIC_API_KEY=sk-ant-...`);
    }
    if (options.providers.openai.enabled && !options.providers.openai.apiKey) {
      console.log(`    ${step++}. Set your OpenAI key: export JOULE_OPENAI_API_KEY=sk-...`);
    }
    if (options.providers.google.enabled && !options.providers.google.apiKey) {
      console.log(`    ${step++}. Set your Google key: export JOULE_GOOGLE_API_KEY=...`);
    }

    console.log(`    ${step++}. Test your setup: joule doctor`);
    console.log(`    ${step++}. Start chatting: joule chat`);
    console.log('');
  });
